
name: 'recharge_source'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

vars:
  recharge_source:
    address: "{{ source('recharge','address') }}"
    address_shipping_line: "{{ source('recharge','address_shipping_line') }}"
    charge: "{{ source('recharge','charge') }}"
    charge_discount_code: "{{ source('recharge','charge_discount_code') }}"
    charge_line_item: "{{ source('recharge','charge_line_item') }}"
    charge_note_attribute: "{{ source('recharge','charge_note_attribute') }}"
    charge_shipping_line: "{{ source('recharge','charge_shipping_line') }}"
    checkout: "{{ source('recharge','checkout') }}"
    checkout_line_item: "{{ source('recharge','checkout_line_item') }}"
    customer: "{{ source('recharge','customer') }}"
    discount: "{{ source('recharge','discount') }}"
    one_time_product: "{{ source('recharge','one_time_product') }}"
    order: "{{ source('recharge','order') }}"
    order_line_item: "{{ source('recharge','order_line_item') }}"
    payment_source: "{{ source('recharge','payment_source') }}"
    product: "{{ source('recharge','product') }}"
    subscription: "{{ source('recharge','subscription') }}"
    subscription_history: "{{ source('recharge','subscription_history') }}"
    utm_tag: "{{ source('recharge','utm_tag') }}"

models:
  recharge_source:
    tmp:
      materialized: view
    +materialized: table
    +schema: recharge_source