config-version: 2

name: 'recharge_source_integration_tests'
version: '0.1.0'

profile: 'integration_tests' 

vars:
  recharge_source:
    recharge_schema: recharge_source_integration_tests
    recharge_address_identifier: "address_data"
    recharge_address_shipping_line_identifier: "address_shipping_line_data"
    recharge_charge_identifier: "charge_data"
    recharge_charge_discount_code_identifier: "charge_discount_code_data"
    recharge_charge_line_item_identifier: "charge_line_item_data"
    recharge_charge_note_attribute_identifier: "charge_note_attribute_data"
    recharge_charge_shipping_line_identifier: "charge_shipping_line_data"
    recharge_checkout_identifier: "checkout_data"
    recharge_checkout_line_item_identifier: "checkout_line_item_data"
    recharge_customer_identifier: "customer_data"
    recharge_discount_identifier: "discount_data"
    recharge_one_time_product_identifier: "one_time_product_data"
    order: "{{ ref('order_data') }}"
    recharge_order_line_item_identifier: "order_line_item_data"
    recharge_payment_source_identifier: "payment_source_data"
    recharge_product_identifier: "product_data"
    recharge_subscription_identifier: "subscription_data"
    recharge_subscription_history_identifier: "subscription_history_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  recharge_source_integration_tests:
    +column_types:
      _fivetran_synced: "timestamp"
        
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
