config-version: 2

name: 'recharge_source_integration_tests'
version: '0.1.0'

profile: 'integration_tests' 

vars:
  recharge_source:
    recharge_schema: recharge_source_integration_tests
    recharge_address_identifier: "ADDRESS_DATA"
    recharge_address_shipping_line_identifier: "ADDRESS_SHIPPING_LINE_DATA"
    recharge_charge_identifier: "CHARGE_DATA"
    recharge_charge_discount_code_identifier: "CHARGE_DISCOUNT_CODE_DATA"
    recharge_charge_line_item_identifier: "CHARGE_LINE_ITEM_DATA"
    recharge_charge_note_attribute_identifier: "CHARGE_NOTE_ATTRIBUTE_DATA"
    recharge_charge_shipping_line_identifier: "CHARGE_SHIPPING_LINE_DATA"
    recharge_checkout_identifier: "CHECKOUT_DATA"
    recharge_checkout_line_item_identifier: "CHECKOUT_LINE_ITEM_DATA"
    recharge_customer_identifier: "CUSTOMER_DATA"
    recharge_discount_identifier: "DISCOUNT_DATA"
    recharge_one_time_product_identifier: "ONE_TIME_PRODUCT_DATA"
    recharge_order_identifier: "ORDER_DATA"
    recharge_order_line_item_identifier: "ORDER_LINE_ITEM_DATA"
    recharge_payment_source_identifier: "PAYMENT_SOURCE_DATA"
    recharge_product_identifier: "PRODUCT_DATA"
    recharge_subscription_identifier: "SUBSCRIPTION_DATA"
    recharge_subscription_history_identifier: "SUBSCRIPTION_HISTORY_DATA"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  recharge_source_integration_tests:
    +column_types:
      _FIVETRAN_SYNCED: "timestamp"
      CANCELLED_AT: "timestamp"
      CREATED_AT: "timestamp"
      PROCESSED_AT: "timestamp"
      NEXT_CHARGE_SCHEDULED_AT: "timestamp"
      SCHEDULED_AT: "timestamp"
      SUBTOTAL_PRICE: "float"
      TOTAL_PRICE: "float"
      UPDATED_AT: "timestamp"
      ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      ADDRESS_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      CHARGE_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      CHECKOUT_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      CUSTOMER_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      DISCOUNT_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      SHOPIFY_PRODUCT_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      SHOPIFY_VARIANT_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      SUBSCRIPTION_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    CHARGE_DATA:
      +column_types:
        LAST_CHARGE_ATTEMPT_DATE: "timestamp"
        RETRY_DATE: "timestamp"
    CHARGE_LINE_ITEM_DATA:
      +column_types:
        PROPERTY_BUNDLE_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        PROPERTY_WIDGET_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    CHECKOUT_DATA:
      +column_types:
        COMPLETED_AT: "timestamp"
    CUSTOMER_DATA:
      +column_types:
        FIRST_CHARGE_PROCESSED_AT: "timestamp"
    DISCOUNT_DATA:
      +column_types:
        APPLIES_TO_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ENDS_AT: "timestamp"
        STARTS_AT: "timestamp"
    ORDER_DATA:
      +column_types:
        SHIPPED_DATE: "timestamp"
        SHIPPING_DATE: "timestamp"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
